# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "/gh-jekyll-setup" # the subpath of your site, e.g. /blog
# SEO
title: gh-jekyll-setup
email: martin.suszczynski@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My website.
url: "https://suszczynski.github.io" # the base hostname & protocol for your site
twitter_username: Suszczynski_M
github_username:  Suszczynski

# Build settings
markdown: kramdown

sass:
  style: compressed

repository: suszczynski/suszczynski.github.io

paginate: 5

gems:
 - jekyll-coffeescript
 - jekyll-feed
 - jekyll-gist
 - jekyll-github-metadata
 - jekyll-mentions
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jemoji

whitelist:
 - jekyll-coffeescript
 - jekyll-feed
 - jekyll-gist
 - jekyll-github-metadata
 - jekyll-mentions
 - jekyll-redirect-from 
 - jekyll-seo-tag
 - jekyll-sitemap
 - jemoji
